config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  scope :public, module: :public do
    get '/calendars/' => 'calendars#index', as: :public_calendars
    get '/calendars/events(.format)' => 'calendars#events', as: :public_calendars_events
  end

  resources :filter_bookmarks do
    get '/link/:code/:link' => 'filter_bookmarks#link', as: :link, on: :collection
  end

  scope :api, module: :api do
    resources :tokens do
      collection do
        post :validation
      end
    end
  end

  get '/auth/:provider/callback', :to => 'o_auth#callback'
  get '/auth/failure', :to => 'o_auth#failure'

  post 'authenticate', :to => 'welcome#authenticate'
  post '/signin', :to => 'welcome#signin'
  get '/signout', :to => 'welcome#signout'

  get '/dashboard', :to => 'dashboard#index'

  resources :event_properties do
    put :sort, on: :collection
  end
  resources :event_property_options, except: [:index]
  resources :contacts do
    get 'suggest/:event_id', to: 'contacts#suggest', on: :collection, as: :suggest
  end

  resources :performance_metrics
  resources :performance_metric_entries, only: [:new, :edit, :create, :update, :destroy]

  resources :events do
    member do
      get :add_attendee, :expenses, :attachments
      get :approved
      get :committed
      get :archived

      get :sharing

      delete 'contacts/:contact_id', to: 'event_contacts#destroy', as: :contact
      post 'contacts/:contact_id', to: 'event_contacts#create'
    end
    collection do
      get :archive
      get :list

      get :export
      post :export, to: 'events#generate_export'

      resources :event_talks, :controller => :event_talks, :as => :event_talks
      resources :attendees, :controller => :attendees
      resources :expenses, :controller => :expenses
      resources :event_notes, :controller => :event_notes
    end
  end

  resources :team_events

  resources :profile_pictures, except: [:index, :edit, :update] do
    member do
      post :set_default, :toggle_public
      get :download
    end
    collection do
      post :set_gravatar
    end
  end

  resources :user_emails
  resources :identities

  resources :biographies, except: [:index, :show] do
    member do
      post :set_default
    end
  end

  resources :users do
    get 'email_confirmation'
    member do
      get 'biographies'
      get 'avatars'
      get 'calendars'
      get 'dump'
    end
  end

  resources :languages, only: [:index]

  resources :warehouse_transactions, except: [:index]
  resources :warehouse_batches, only: [:show, :edit, :create, :update, :destroy] do
    collection do
      get :autocomplete
    end

    resources :warehouse_transactions, only: [:new, :index], path: :transactions
  end
  resources :warehouse_items, only: [:show, :edit, :create, :update, :destroy] do
    resources :warehouse_batches, only: [:new, :index], path: :batches
  end
  resources :warehouses do
    resources :warehouse_items, only: [:new, :index], path: :items
  end

  resources :tags do
    collection do
      post :populate
    end
  end

  get 'taggeds/:item/:id' => "taggeds#edit", as: :edit_tags
  patch 'taggeds/:item/:id' => "taggeds#update", as: :update_tags

  resources :talks do
    member do
      get 'archive'
    end
  end

  resources :calendars do
    collection do
      get 'events'
      get 'talks'
      get 'user/talks', :action => :user_talks
      get 'user'
    end
    member do
      get 'events'
      get 'ical'
    end
  end

  resources :attachments do

  end

  resources :roles do
    member do
      post :set_default
    end

    collection do
      get 'edit_user/:user_id' => 'roles#edit_user_roles', as: :edit_user
      patch 'user/:user_id' => 'roles#update_user_roles', as: :update_user
    end
  end

  resource :geo do
    resources :cities
    resources :countries
    resources :continents
  end

  resources :form_submissions

  resources :forms do
    member do
      get :submissions
    end

    get 'submit(/:associated_object_type/:associated_object_id)' => 'form_submissions#new', as: :submit
  end

  resources :event_types do
    post 'default'
  end

  resources :teams do
    resources :members, :controller => :team_members, :as => :team_members

    resources :attendee_types do
      post 'default'
    end

    resources :expense_types do
      post 'default'
    end

    member do
      get 'select'
      get 'settings'
      get 'dump'
    end

    collection do
      get 'statistics'
      get 'slack'
      get 'slack/sync', :action => :slack_sync

      resources :invitations, :controller => :team_invitations, :as => :team_invitations do
        member do
          get 'accept'
          get 'decline'
        end
      end
    end
  end

  post '/slack/:action', :controller => 'slack'

end

app/models/talk.rb
class Talk < ApplicationRecord

  belongs_to  :team
  belongs_to  :user
  belongs_to  :event_type

  has_many :event_talks, dependent: :destroy
  has_many :events, :through => :event_talks

  has_many  :taggeds, :as => :item, dependent: :destroy, inverse_of: :item
  has_many  :tags, -> { distinct }, :through => :taggeds

  validates :name, presence: true
  validates :event_type, presence: true
  validates :user, presence: true
  validates :team, presence: true

  authorize_values_for :user
  authorize_values_for :event_type
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController

  before_action :require_modal, only: [:new, :edit]

  def index
    respond_to do |format|
      format.html do
        @recent = Talk.where(:team_id => current_team.id, :archived => false).order(:created_at => :desc).limit(5).all
        @my = Talk.where(:user => current_user, :archived => false).order(:created_at => :desc).all
      end
      format.json do
        @talks = Talk.where(:team_id => current_team.id, :archived => false)
        @talks = @talks.where('LOWER(name) LIKE ? AND archived=?', "%#{params[:q][:term].downcase}%", false) if params[:q]
        render :json => @talks
      end
    end
  end

  def new
    @talk = Talk.new
    @talk.user = current_user
    @talk.event_type = current_team.default_event_type

    respond_to :html
  end

  def create
    @talk = Talk.new(talk_params)
    @talk.team = current_team
    authorize! @talk, :create

    if @talk.save
      redirect_to @talk
    else
      render action: :new
    end
  end

  def show
    @talk = Talk.find(params[:id])
    authorize! @talk, :read
  end

  def edit
    @talk = Talk.find(params[:id])
    authorize! @talk, :update
  end

  def update
    @talk = Talk.find(params[:id])
    authorize! @talk, :update

    if @talk.update_attributes talk_params
      redirect_to @talk
    else
      render action: :edit
    end
  end

  def destroy
    @talk = Talk.find(params[:id])
    authorize! @talk, :destroy
    @talk.destroy

    redirect_to(talks_path)
  end


  private
  def talk_params
    params.require(:talk).permit(:name, :abstract, :user_id, :event_type_id, :archived)
  end

end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_form.html.erb
<%= form_for(@talk,
             html: { class: 'form-horizontal' },
             data: {
                 js:    { render_class: "EvMan.Views.Talks.Edit" },
                 modal: { render_type: :replace }
             }) do |form| %>

    <div class="modal-header">
      <h4 class="modal-title"><%= title if defined? title %></h4>
    </div>

    <div class="modal-body">
      <%= validation_errors @talk %>

      <div class="form-group row">
        <label class="col-form-label col-lg-2">Name</label>
        <div class="col-lg-10">
          <%= form.text_field(:name, :class => 'form-control') %>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-form-label col-lg-2">Type</label>
        <div class="col-lg-10">
          <%= form.collection_select :event_type_id, form.object.assignable_event_types, :id, :name %>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-form-label col-lg-2">Owner</label>
        <div class="col-lg-10">
          <%= form.collection_select :user_id, form.object.assignable_users, :id, :name %>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-form-label col-lg-2">Abstract</label>
        <div class="col-lg-10">
          <%= form.text_area(:abstract, :class => 'form-control', :rows => 10) %>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-lg-2 col-form-label">State</label>
        <div class="col-lg-10">
          <div class="checkbox"><label><%= form.check_box(:archived) %> Archived</label></div>
        </div>
      </div>

    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-default modal-close">Close</button>
      <%= form.submit "Save", class: "btn btn-success" %>
    </div>
<% end %>

app/views/talks/edit.html.erb
<%= render partial: 'form', locals: { title: 'Edit talk'} %>

app/views/talks/index.html.erb
<% breadcrumb_nav.add_item "Talks" %>

<style type="text/css">
    #search_for_talk_results {
        margin-top: 15px;
    }
</style>

<%= content_tag :div, class: "row", data: { js: { render_class: "EvMan.Views.Talks.Index" }} do %>
    <div class="col-lg-9">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">
                        My talks
                    </div>
                      <ul class="list-group list-group-flush">
                          <% @my.each do |talk| %>
                              <li class="list-group-item">
                                  <div class="hideOverflow">
                                      <span class="hideOverflow"><a href="<%= talk_path(talk) %>"><%= talk.name %></a></span>
                                  </div>
                              </li>
                          <% end %>
                      </ul>
                </div>
            </div>
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header">
                Most recent talks
              </div>
              <ul class="list-group list-group-flush">
                <% @recent.each do |talk| %>
                    <li class="list-group-item">
                      <div class="hideOverflow">
                        <span class="hideOverflow"><a href="<%= talk_path(talk) %>"><%= talk.name %></a></span>
                      </div>
                    </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="card">
            <div class="card-header">
                Search talks by name
            </div>
            <div class="card-block">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for..." id="search_for_talk">
              </div>
            </div>
            <div id="search_for_talk_results"></div>
        </div>
    </div>

<% end %>

app/views/talks/new.html.erb
<%= render partial: 'form', locals: { title: 'New talk'} %>

app/views/talks/show.html.erb
<%
  breadcrumb_nav.add_item "Talks", talks_path
  breadcrumb_nav.add_item @talk.name
%>

<%= content_tag :div, class: "row", data: { js: { render_class: "EvMan.Views.Talks.Show" }} do %>
    <div class="col-lg-6">

        <div class="card">

            <div class="card-header">
                <div>
                    <%= @talk.name %>
                    <div class="pull-right">
                      <%= link_to edit_talk_path(@talk), data: {modal: true }, class: 'btn btn-warning btn-sm' do %>
                          <%= icon(:edit, :fa) %> Edit talk
                      <% end %>
                      <%= link_to @talk, method: :delete,
                                  data:         {
                                      confirm: {
                                          title:    "Delete talk",
                                          question: "Are you sure you want to delete this talk ?"
                                      }
                                  },
                                  class:        "btn btn-danger btn-sm" do %>
                          <%= icon(:remoev, :fa) %> Delete talk
                      <% end %>
                    </div>
                </div>
            </div>

            <div class="card-block">

                <dl class="dl-horizontal">
                    <dt>Owner</dt>
                    <dd><a href="<%= user_path(@talk.user) %>"><%= @talk.user.name %></a> </dd>
                </dl>

                <dl class="dl-horizontal">
                    <dt>Event Type</dt>
                    <dd><%= @talk.event_type.name %></dd>
                </dl>

                <dl class="dl-horizontal">
                    <dt>Abstract</dt>
                    <dd><%= markdown(@talk.abstract) %></dd>
                </dl>

            </div>
        </div>

    </div>

    <div class="col-lg-6">

        <div class="card">
            <div class="card-header">
                Events
                <div class="pull-right">
                  <%= link_to new_event_talk_path(talk_id: @talk.id), data: {modal: true }, class: 'btn btn-success btn-sm' do %>
                      <%= icon(:plus, :fa) %> Add talk
                  <% end %>
                </div>
            </div>
            <div class="card-block no-padding">
                <ul class="list-group">
                    <% @talk.event_talks.each do |talk| %>
                        <li class="list-group-item" id="talk<%= talk.id %>">
                            <div class="row" style="padding-bottom: 5px;">
                                <div class="col-lg-1" style="text-align: right;">
                                    <div class="dropdown">
                                        <button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  class="btn btn-outline-secondary btn-sm">
                                          <i class="fa fa-caret-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                                            <li>
                                              <%= link_to edit_event_talk_path(talk), data: {modal: true }, class: 'dropdown-item' do %>
                                                <%= icon(:edit, :fa) %> Edit talk
                                              <% end %>
                                            </li>
                                            <li>
                                              <%= link_to talk,
                                                          method: :delete,
                                                          data: {
                                                              confirm: {
                                                                  title: "Remove talk",
                                                                  question: "Are you sure you want to remove this talk?"
                                                              }
                                                          },
                                                          class: 'dropdown-item' do %>
                                                <%= icon(:remove, :fa) %> &nbsp; Remove talk
                                              <% end %>
                                            </li>
                                        </ul>
                                    </div>
                                </div>

                                <div class="col-lg-6" style="font-weight: bold;">
                                    <div class="hideOverflow">
                                      <% if talk.event %>
                                        <a href="<%= event_path(talk.event) %>"><%= talk.event.name %></a>
                                      <% end %>
                                    </div>
                                </div>

                                <div class="col-lg-2" style="font-weight: bold;">
                                    <div class="pull-right">
                                        <% if talk.state == nil %><span class="label label-warning">Undecided</span><% end %>
                                        <% if talk.state == true %><span class="label label-success">Accepted</span><% end %>
                                        <% if talk.state == false %><span class="label label-danger">Rejected</span><% end %>
                                    </div>
                                </div>

                                <div class="col-lg-3">
                                    <a href="<%= user_path(talk.user) %>"><%= talk.user.name %></a>
                                </div>
                            </div>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
      <div class="card">
        <div class="card-header">
          Tags
          <%= link_to edit_tags_path(:talk, @talk.id),
                      data: { modal: true },
                      class: 'btn btn-warning btn-sm pull-right' do %>
              <%= icon(:edit, :fa) %> Edit
          <% end %>
        </div>
        <div class="card-block">
          <% @talk.tags.each do |tag| %>
              <span class="tag tag-default"><%= tag.name %></span>
          <% end %>
        </div>
      </div>
    </div>
<% end %>