config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  scope :public, module: :public do
    get '/calendars/' => 'calendars#index', as: :public_calendars
    get '/calendars/events(.format)' => 'calendars#events', as: :public_calendars_events
  end

  resources :filter_bookmarks do
    get '/link/:code/:link' => 'filter_bookmarks#link', as: :link, on: :collection
  end

  scope :api, module: :api do
    resources :tokens do
      collection do
        post :validation
      end
    end
  end

  get '/auth/:provider/callback', :to => 'o_auth#callback'
  get '/auth/failure', :to => 'o_auth#failure'

  post 'authenticate', :to => 'welcome#authenticate'
  post '/signin', :to => 'welcome#signin'
  get '/signout', :to => 'welcome#signout'

  get '/dashboard', :to => 'dashboard#index'

  resources :event_properties do
    put :sort, on: :collection
  end
  resources :event_property_options, except: [:index]
  resources :contacts do
    get 'suggest/:event_id', to: 'contacts#suggest', on: :collection, as: :suggest
  end

  resources :performance_metrics
  resources :performance_metric_entries, only: [:new, :edit, :create, :update, :destroy]

  resources :events do
    member do
      get :add_attendee, :expenses, :attachments
      get :approved
      get :committed
      get :archived

      get :sharing

      delete 'contacts/:contact_id', to: 'event_contacts#destroy', as: :contact
      post 'contacts/:contact_id', to: 'event_contacts#create'
    end
    collection do
      get :archive
      get :list

      get :export
      post :export, to: 'events#generate_export'

      resources :event_talks, :controller => :event_talks, :as => :event_talks
      resources :attendees, :controller => :attendees
      resources :expenses, :controller => :expenses
      resources :event_notes, :controller => :event_notes
    end
  end

  resources :team_events

  resources :profile_pictures, except: [:index, :edit, :update] do
    member do
      post :set_default, :toggle_public
      get :download
    end
    collection do
      post :set_gravatar
    end
  end

  resources :user_emails
  resources :identities

  resources :biographies, except: [:index, :show] do
    member do
      post :set_default
    end
  end

  resources :users do
    get 'email_confirmation'
    member do
      get 'biographies'
      get 'avatars'
      get 'calendars'
      get 'dump'
    end
  end

  resources :languages, only: [:index]

  resources :warehouse_transactions, except: [:index]
  resources :warehouse_batches, only: [:show, :edit, :create, :update, :destroy] do
    collection do
      get :autocomplete
    end

    resources :warehouse_transactions, only: [:new, :index], path: :transactions
  end
  resources :warehouse_items, only: [:show, :edit, :create, :update, :destroy] do
    resources :warehouse_batches, only: [:new, :index], path: :batches
  end
  resources :warehouses do
    resources :warehouse_items, only: [:new, :index], path: :items
  end

  resources :tags do
    collection do
      post :populate
    end
  end

  get 'taggeds/:item/:id' => "taggeds#edit", as: :edit_tags
  patch 'taggeds/:item/:id' => "taggeds#update", as: :update_tags

  resources :talks do
    member do
      get 'archive'
    end
  end

  resources :calendars do
    collection do
      get 'events'
      get 'talks'
      get 'user/talks', :action => :user_talks
      get 'user'
    end
    member do
      get 'events'
      get 'ical'
    end
  end

  resources :attachments do

  end

  resources :roles do
    member do
      post :set_default
    end

    collection do
      get 'edit_user/:user_id' => 'roles#edit_user_roles', as: :edit_user
      patch 'user/:user_id' => 'roles#update_user_roles', as: :update_user
    end
  end

  resource :geo do
    resources :cities
    resources :countries
    resources :continents
  end

  resources :form_submissions

  resources :forms do
    member do
      get :submissions
    end

    get 'submit(/:associated_object_type/:associated_object_id)' => 'form_submissions#new', as: :submit
  end

  resources :event_types do
    post 'default'
  end

  resources :teams do
    resources :members, :controller => :team_members, :as => :team_members

    resources :attendee_types do
      post 'default'
    end

    resources :expense_types do
      post 'default'
    end

    member do
      get 'select'
      get 'settings'
      get 'dump'
    end

    collection do
      get 'statistics'
      get 'slack'
      get 'slack/sync', :action => :slack_sync

      resources :invitations, :controller => :team_invitations, :as => :team_invitations do
        member do
          get 'accept'
          get 'decline'
        end
      end
    end
  end

  post '/slack/:action', :controller => 'slack'

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggeds, dependent: :destroy
  belongs_to :team

  validates :name, presence: true

  before_validation :set_keyword

  def set_keyword
    self.keyword = name.downcase
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    respond_to do |format|
      format.json do
        tags = current_team.tags.where('lower(name) LIKE ?', "#{params[:q].downcase}%").all.map do |tag|
          {:id => tag.id, :text => tag.name}
        end
        render :json => tags
      end
      format.html do
        @counts = Tagged.joins(:tag).where(tags: { team_id: current_team.id }).group(:tag_id).count
        @populate_form = TagServices::PopulateForm.new({}, current_team)
        @tags = current_team.tags.order(name: :asc)
      end
    end
  end

  def populate
    @populate_form = TagServices::PopulateForm.new populate_params, current_team
    @populate_form.submit
    redirect_to action: :index
  end

  def new
    @tag = Tag.new

    respond_to :html
  end

  def create
    @tag = Tag.new
    authorize! @tag, :create
    @tag.name = params[:tag][:name]
    @tag.keyword = params[:tag][:name].downcase
    @tag.team = current_team
    if @tag.save
      redirect_to(tags_path)
    else
      render action: :new
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    authorize! @tag, :destroy
    @tag.destroy

    redirect_to(tags_path)
  end

  private

  def populate_params
    params.require(:populate_form).permit(tag_names: [])
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for @populate_form, url: populate_tags_path, class:'form form-horizontal', data: {
    js: {
        render_class: "EvMan.Views.Tags.PopulateForm"
    }
} do |form| %>
  <div class="card">
    <div class="card-header">
      Create new Tags
    </div>
    <div class="card-block">

      <%= validation_errors form.object %>

      <div class="form-group row">
        <label class="col-form-label col-lg-2">Names</label>
        <div class="col-lg-10">
          <%= form.select(:tag_names, [], {class: 'form-control'}, multiple: true) %>
        </div>
      </div>
      <div class="form-group">
          <%= form.submit 'Create tags', class: 'btn btn-success btn-sm pull-right' %>
      </div>
    </div>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<li class="list-group-item">
  <div class="row">
    <div class="col-lg-9">
      <%= tag.name %>
    </div>
    <div class="col-lg-1">
      <% if @counts[tag.id] %>
          <span class="badge badge-primary" title="Tagged records"><%= @counts[tag.id] %></span>
      <% end %>
    </div>
    <div class="col-lg-2">
      <%= link_to tag, method: :delete,
                  title: 'Remove',
                  data: {
                      confirm: {
                          question: 'Are you sure you want to remove this tag ?',
                          title: 'Remove tag'
                      }
                  },
                  class: 'btn btn-danger btn-sm pull-right' do %>
          <%= icon(:remove, :fa) %> Remove
      <% end %>
    </div>
  </div>
</li>

app/views/tags/index.html.erb
<%
  breadcrumb_nav.add_item 'Team'
  breadcrumb_nav.add_item current_team.name, team_path(current_team)
  breadcrumb_nav.add_item 'Tags'
%>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header">
          Tags
        </div>

        <ul class="list-group list-group-flush">
          <%= render @tags %>
        </ul>

        <div class="card-footer">
          <small>By removing Tag from this list, you will also remove it from every associated record.</small>
        </div>
      </div>
    </div>

    <div class="col-lg-6">
      <%= render 'form' %>
    </div>
  </div>

</div>

app/views/tags/new.html.erb
<%= render 'form' %>