config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  scope :public, module: :public do
    get '/calendars/' => 'calendars#index', as: :public_calendars
    get '/calendars/events(.format)' => 'calendars#events', as: :public_calendars_events
  end

  resources :filter_bookmarks do
    get '/link/:code/:link' => 'filter_bookmarks#link', as: :link, on: :collection
  end

  scope :api, module: :api do
    resources :tokens do
      collection do
        post :validation
      end
    end
  end

  get '/auth/:provider/callback', :to => 'o_auth#callback'
  get '/auth/failure', :to => 'o_auth#failure'

  post 'authenticate', :to => 'welcome#authenticate'
  post '/signin', :to => 'welcome#signin'
  get '/signout', :to => 'welcome#signout'

  get '/dashboard', :to => 'dashboard#index'

  resources :event_properties do
    put :sort, on: :collection
  end
  resources :event_property_options, except: [:index]
  resources :contacts do
    get 'suggest/:event_id', to: 'contacts#suggest', on: :collection, as: :suggest
  end

  resources :performance_metrics
  resources :performance_metric_entries, only: [:new, :edit, :create, :update, :destroy]

  resources :events do
    member do
      get :add_attendee, :expenses, :attachments
      get :approved
      get :committed
      get :archived

      get :sharing

      delete 'contacts/:contact_id', to: 'event_contacts#destroy', as: :contact
      post 'contacts/:contact_id', to: 'event_contacts#create'
    end
    collection do
      get :archive
      get :list

      get :export
      post :export, to: 'events#generate_export'

      resources :event_talks, :controller => :event_talks, :as => :event_talks
      resources :attendees, :controller => :attendees
      resources :expenses, :controller => :expenses
      resources :event_notes, :controller => :event_notes
    end
  end

  resources :team_events

  resources :profile_pictures, except: [:index, :edit, :update] do
    member do
      post :set_default, :toggle_public
      get :download
    end
    collection do
      post :set_gravatar
    end
  end

  resources :user_emails
  resources :identities

  resources :biographies, except: [:index, :show] do
    member do
      post :set_default
    end
  end

  resources :users do
    get 'email_confirmation'
    member do
      get 'biographies'
      get 'avatars'
      get 'calendars'
      get 'dump'
    end
  end

  resources :languages, only: [:index]

  resources :warehouse_transactions, except: [:index]
  resources :warehouse_batches, only: [:show, :edit, :create, :update, :destroy] do
    collection do
      get :autocomplete
    end

    resources :warehouse_transactions, only: [:new, :index], path: :transactions
  end
  resources :warehouse_items, only: [:show, :edit, :create, :update, :destroy] do
    resources :warehouse_batches, only: [:new, :index], path: :batches
  end
  resources :warehouses do
    resources :warehouse_items, only: [:new, :index], path: :items
  end

  resources :tags do
    collection do
      post :populate
    end
  end

  get 'taggeds/:item/:id' => "taggeds#edit", as: :edit_tags
  patch 'taggeds/:item/:id' => "taggeds#update", as: :update_tags

  resources :talks do
    member do
      get 'archive'
    end
  end

  resources :calendars do
    collection do
      get 'events'
      get 'talks'
      get 'user/talks', :action => :user_talks
      get 'user'
    end
    member do
      get 'events'
      get 'ical'
    end
  end

  resources :attachments do

  end

  resources :roles do
    member do
      post :set_default
    end

    collection do
      get 'edit_user/:user_id' => 'roles#edit_user_roles', as: :edit_user
      patch 'user/:user_id' => 'roles#update_user_roles', as: :update_user
    end
  end

  resource :geo do
    resources :cities
    resources :countries
    resources :continents
  end

  resources :form_submissions

  resources :forms do
    member do
      get :submissions
    end

    get 'submit(/:associated_object_type/:associated_object_id)' => 'form_submissions#new', as: :submit
  end

  resources :event_types do
    post 'default'
  end

  resources :teams do
    resources :members, :controller => :team_members, :as => :team_members

    resources :attendee_types do
      post 'default'
    end

    resources :expense_types do
      post 'default'
    end

    member do
      get 'select'
      get 'settings'
      get 'dump'
    end

    collection do
      get 'statistics'
      get 'slack'
      get 'slack/sync', :action => :slack_sync

      resources :invitations, :controller => :team_invitations, :as => :team_invitations do
        member do
          get 'accept'
          get 'decline'
        end
      end
    end
  end

  post '/slack/:action', :controller => 'slack'

end

app/models/warehouse_item.rb
class WarehouseItem < ApplicationRecord
  belongs_to :warehouse, inverse_of: :items
  has_many :batches, class_name: 'WarehouseBatch', foreign_key: :item_id, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: [:warehouse_id], case_sensitive: false }

  def concerned_teams
    warehouse.concerned_teams
  end

end

app/controllers/warehouse_items_controller.rb
class WarehouseItemsController < ApplicationController
  before_action :find_warehouse, only: [:index, :new]
  before_action :require_modal, only: [:new, :edit]

  def index
    @items = @warehouse.items.order(:name)
    @counts = WarehouseBatch.where(item_id: @items.select(:id)).group(:item_id).sum(:total)
  end

  def show
    redirect_to warehouse_item_warehouse_batches_path(params[:id])
  end

  def new
    @item = @warehouse.items.build

    respond_to :html
  end

  def create
    @item = WarehouseItem.new(item_params)

    if @item.save
      redirect_to @item.warehouse
    else
      render action: :new
    end
  end

  def edit
    @item = WarehouseItem.find(params[:id])

    respond_to :html
  end

  def update
    @item = WarehouseItem.find(params[:id])
    @item.attributes = item_params

    if @item.save
      redirect_to @item.warehouse
    else
      render action: :edit
    end
  end

  def destroy
    @item = WarehouseItem.find(params[:id])
    @item.destroy

    redirect_to @item.warehouse
  end

  private
  def item_params
    params.require(:warehouse_item).permit(:name, :warehouse_id)
  end

  def find_warehouse
    @warehouse = current_team.warehouses.find(params[:warehouse_id])
  end
end

app/views/warehouse_items/_form.html.erb
<%= form_for @item, data: { modal: { render_type: :replace } } do |f| %>
    <%= f.hidden_field :warehouse_id %>
    <div class="modal-header">
      <h4 class="modal-title">Item</h4>
    </div>

    <div class="modal-body">

      <%= validation_errors(@item) %>

      <div class="form-group row">
        <%= f.label :name, "Name", class: "col-form-label col-lg-2" %>
        <div class=" col-lg-10">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="clearfix"></div>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-default modal-close">Close</button>
      <%= f.submit "Save", class: "btn btn-success" %>
    </div>
<% end %>

app/views/warehouse_items/_warehouse_item.html.erb
<tr>
  <th scope="row">
    <%= link_to edit_warehouse_item_path(warehouse_item), class: 'btn btn-warning btn-xs', data: { modal: true } do %>
        <%= icon(:edit, :fa) %> Edit
    <% end %>

    <%= link_to warehouse_item_path(warehouse_item), class: 'btn btn-danger btn-xs',
                method: :delete,
                data: {
                    confirm: {
                        title: "Remove item",
                        question: "Are you sure you want to remove this item ?"
                    }
                } do %>
        <%= icon(:remove, :fa) %> Remove
    <% end %>
  </th>

  <td>
    <%= link_to warehouse_item.name, warehouse_item_path(warehouse_item), class: 'blue-link' %>
  </td>
  <td><%= @counts[warehouse_item.id] %></td>
</tr>

app/views/warehouse_items/edit.html.erb
<%= render 'form' %>

app/views/warehouse_items/index.html.erb
<%
  breadcrumb_nav.add_item 'Warehouses'
  breadcrumb_nav.add_item @warehouse.name, warehouse_path(@warehouse)
%>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <div class="card card-block no-padding">
        <table class="table table-hover">
          <tr>
            <th>
              <%= link_to new_warehouse_warehouse_item_path(@warehouse), class: 'btn btn-success btn-xs', data: { modal: true } do %>
                  <%= icon(:plus, :fa) %> New Item
              <% end %>
            </th>
            <th>Name</th>
            <th>Count</th>
          </tr>

          <tbody>
          <%= render @items %>
          </tbody>

        </table>
      </div>
    </div>
  </div>
</div>

app/views/warehouse_items/new.html.erb
<%= render 'form' %>